# Generated by Django 4.1 on 2023-03-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("num_soldiers", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("is_captain", models.BooleanField(default=False)),
                ("has_seasickness", models.BooleanField(default=False)),
                ("ship", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game_app.ship")),
            ],
        ),
        migrations.AddField(
            model_name="ship",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captain",
                to="game_app.soldier",
            ),
        ),
    ]
