# Generated by Django 4.1 on 2023-03-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_soldiers', models.IntegerField()),
                ('eligible_soldiers', models.IntegerField()),
                ('seasickness_soldiers', models.IntegerField(default=0)),
                ('death_soldiers', models.IntegerField(default=0)),
                ('destroyed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'destroyed')},
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='game_app.ship')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='game_app.ship')),
            ],
            options={
                'unique_together': {('attacker', 'defender')},
            },
        ),
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.battle')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='game_app.ship')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game_app.ship')),
            ],
            options={
                'unique_together': {('battle',)},
            },
        ),
    ]
