# Generated by Django 4.1 on 2023-03-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.AddField(
            model_name="ship",
            name="death_soldiers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ship",
            name="destroyed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ship",
            name="eligible_soldiers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ship",
            name="seasickness_soldiers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="ship",
            unique_together={("name", "destroyed")},
        ),
        migrations.CreateModel(
            name="BattleResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("battle", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="game_app.battle")),
                (
                    "loser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="loser", to="game_app.ship"
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="winner", to="game_app.ship"
                    ),
                ),
            ],
            options={
                "unique_together": {("battle",)},
            },
        ),
        migrations.AddField(
            model_name="battle",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attacker", to="game_app.ship"
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="defender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="defender", to="game_app.ship"
            ),
        ),
        migrations.RemoveField(
            model_name="ship",
            name="captain",
        ),
        migrations.DeleteModel(
            name="Soldier",
        ),
        migrations.AlterUniqueTogether(
            name="battle",
            unique_together={("attacker", "defender")},
        ),
    ]
